package com.wgh.aiyue.greendao;

import com.wgh.aiyue.model.Category;
import com.wgh.aiyue.model.FavoriteCat;
import com.wgh.aiyue.model.ImgCat;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig favoriteCatDaoConfig;
    private final DaoConfig imgCatDaoConfig;

    private final CategoryDao categoryDao;
    private final FavoriteCatDao favoriteCatDao;
    private final ImgCatDao imgCatDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        favoriteCatDaoConfig = daoConfigMap.get(FavoriteCatDao.class).clone();
        favoriteCatDaoConfig.initIdentityScope(type);

        imgCatDaoConfig = daoConfigMap.get(ImgCatDao.class).clone();
        imgCatDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        favoriteCatDao = new FavoriteCatDao(favoriteCatDaoConfig, this);
        imgCatDao = new ImgCatDao(imgCatDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(FavoriteCat.class, favoriteCatDao);
        registerDao(ImgCat.class, imgCatDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        favoriteCatDaoConfig.clearIdentityScope();
        imgCatDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public FavoriteCatDao getFavoriteCatDao() {
        return favoriteCatDao;
    }

    public ImgCatDao getImgCatDao() {
        return imgCatDao;
    }

}
